version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/tools"
    schedule:
      interval: "weekly"
