format:
	npm run format

check:
	npm run check

website:
	python3 ./make-website-content.py

website-deploy:
	cd ../website && npm run deploy

website-preview:
	cd ../website && npm run build && npm run preview

books:
	./make-books.sh